/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminMatriculasRouteImport } from './routes/admin.matriculas'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminProfessoresRouteImport } from './routes/admin.professores'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminTurmasRouteImport } from './routes/admin.turmas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatriculasRoute = AdminMatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessoresRoute = AdminProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTurmasRoute = AdminTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/matriculas': typeof AdminMatriculasRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/turmas': typeof AdminTurmasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/matriculas': typeof AdminMatriculasRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/turmas': typeof AdminTurmasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/matriculas': typeof AdminMatriculasRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/turmas': typeof AdminTurmasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/admin/alunos'
    | '/admin/avaliacoes'
    | '/admin/cursos'
    | '/admin/matriculas'
    | '/admin/modulos'
    | '/admin/professores'
    | '/admin/relatorios'
    | '/admin/turmas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/admin/alunos'
    | '/admin/avaliacoes'
    | '/admin/cursos'
    | '/admin/matriculas'
    | '/admin/modulos'
    | '/admin/professores'
    | '/admin/relatorios'
    | '/admin/turmas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/admin/alunos'
    | '/admin/avaliacoes'
    | '/admin/cursos'
    | '/admin/matriculas'
    | '/admin/modulos'
    | '/admin/professores'
    | '/admin/relatorios'
    | '/admin/turmas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matriculas': {
      id: '/admin/matriculas'
      path: '/matriculas'
      fullPath: '/admin/matriculas'
      preLoaderRoute: typeof AdminMatriculasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professores': {
      id: '/admin/professores'
      path: '/professores'
      fullPath: '/admin/professores'
      preLoaderRoute: typeof AdminProfessoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/turmas': {
      id: '/admin/turmas'
      path: '/turmas'
      fullPath: '/admin/turmas'
      preLoaderRoute: typeof AdminTurmasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminMatriculasRoute: typeof AdminMatriculasRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminProfessoresRoute: typeof AdminProfessoresRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminTurmasRoute: typeof AdminTurmasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminMatriculasRoute: AdminMatriculasRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminProfessoresRoute: AdminProfessoresRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminTurmasRoute: AdminTurmasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
